- name: Allow vpn
  command: firewall-cmd --zone=public --permanent --add-port=1195/tcp  --add-port=1195/udp 

- name: Bounce firewalld
  service: name=firewalld state=restarted
  when: "'con01' not in inventory_hostname_short"